// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvDpgaFNM-hhi2XpdYdmb7fcBrt-nwK-Q',
    appId: '1:834370387943:ios:d66a5a8d6812f4694e4742',
    messagingSenderId: '834370387943',
    projectId: 'study-hub-3210f',
    storageBucket: 'study-hub-3210f.firebasestorage.app',
    iosBundleId: 'com.example.semesteProject',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvDpgaFNM-hhi2XpdYdmb7fcBrt-nwK-Q',
    appId: '1:834370387943:ios:d66a5a8d6812f4694e4742',
    messagingSenderId: '834370387943',
    projectId: 'study-hub-3210f',
    storageBucket: 'study-hub-3210f.firebasestorage.app',
    iosBundleId: 'com.example.semesteProject',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvwLmhTVkUvnJ3d-BEf1JcHDqVA3t0Upo',
    appId: '1:834370387943:web:763f5d65464843b44e4742',
    messagingSenderId: '834370387943',
    projectId: 'study-hub-3210f',
    authDomain: 'study-hub-3210f.firebaseapp.com',
    storageBucket: 'study-hub-3210f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq0tUfhFVHsqUKapirI18wogi403FFZ70',
    appId: '1:834370387943:android:325ea07eb104bf824e4742',
    messagingSenderId: '834370387943',
    projectId: 'study-hub-3210f',
    storageBucket: 'study-hub-3210f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvwLmhTVkUvnJ3d-BEf1JcHDqVA3t0Upo',
    appId: '1:834370387943:web:a9d770c7fd221d524e4742',
    messagingSenderId: '834370387943',
    projectId: 'study-hub-3210f',
    authDomain: 'study-hub-3210f.firebaseapp.com',
    storageBucket: 'study-hub-3210f.firebasestorage.app',
  );
}
